version: "3"
services:
    mysql:
        container_name: mysql
        platform: linux/amd64
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        env_file:
            - .env
        volumes:
            - ./.docker/mysql/data:/var/lib/mysql
            - ./mysql/src:/root/src
        ports:
            - "3306:3306"
        networks:
            - app
        tty: true
        working_dir: /root/src

    elasticsearch:
        container_name: elasticsearch
        image: elasticsearch:7.17.4
        environment:
            xpack.security.enabled: false
            discovery.type: single-node
        ports:
            - "9200:9200"
        networks:
            - app
        tty: true

    kibana:
        container_name: kibana
        image: kibana:7.17.4
        environment:
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        depends_on:
            - elasticsearch
        ports:
            - "5601:5601"
        networks:
            - app

    embulk:
        container_name: embulk
        platform: linux/amd64
        build: ./.docker/embulk
        volumes:
            - ./embulk/src:/root/src
        networks:
            - app
        tty: true
        working_dir: /root/src

networks:
    app:
        driver: bridge
